static_analyses:
  ignore_files: []
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
downstream_dependencies:
  - datanator
  - datanator_rest_api
email_notifications: []
